# 服务端口
server.port=8164
# 服务名
spring.application.name=service-msm

# 发件人邮箱信息
# 发件人账户
spring.mail.username=你们自己的
# 发件人密码
spring.mail.password=你们自己的
# 邮件供应商
spring.mail.host=你们自己的

# nacos服务地址
spring.cloud.nacos.discovery.server-addr=172.31.88.233:8848

# JSON处理时忽略非空字段
spring.jackson.default-property-inclusion=non_null

logging.level.com.hmdp=debug