# ����˿�
server.port=8081
# ������
spring.application.name=service-gateway
# nacosע�����ĵ�ַ
spring.cloud.nacos.discovery.server-addr=172.27.52.12:8848
# ʹ�÷�����·��
spring.cloud.gateway.discovery.locator.enabled=true

# redis����
spring.redis.host=172.27.52.12
spring.redis.port=6379
spring.redis.database= 0
spring.redis.lettuce.pool.max-active=10
spring.redis.lettuce.pool.max-idle=10
spring.redis.lettuce.pool.min-idle=1
spring.redis.lettuce.pool.time-between-eviction-runs=10s

# mysql���ݿ�����
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://172.27.52.12:3306/hmdp?characterEncoding=utf-8&useSSL=false
spring.datasource.username=root
spring.datasource.password=123456

#����mapper xml�ļ���·��
mybatis-plus.mapper-locations=classpath:com/hmdp/voucher/mapper/xml/*.xml
# �����շ�����������ӳ��ʵ���������ʱ�������ݿ��б������ֶ����е��»���ȥ���������շ�������ӳ��
mybatis-plus.configuration.map-underscore-to-camel-case=true

# JSON����ʱ���Էǿ��ֶ�
spring.jackson.default-property-inclusion=non_null

# ���¶�������·������

## ����·��id
#spring.cloud.gateway.routes[0].id=service-user
##����·�ɵ�uri
#spring.cloud.gateway.routes[0].uri=lb://service-user
##����·�ɶ���,����servicerIdΪauth-service��/auth/·��
#spring.cloud.gateway.routes[0].predicates= Path=/user/**
#
## ����·��id
#spring.cloud.gateway.routes[1].id=service-shop
##����·�ɵ�uri
#spring.cloud.gateway.routes[1].uri=lb://service-shop
##����·�ɶ���,����servicerIdΪauth-service��/auth/·��
#spring.cloud.gateway.routes[1].predicates= Path=/shop/**
#
## ����·��id
#spring.cloud.gateway.routes[2].id=service-shop
##����·�ɵ�uri
#spring.cloud.gateway.routes[2].uri=lb://service-shop
##����·�ɶ���,����servicerIdΪauth-service��/auth/·��
#spring.cloud.gateway.routes[2].predicates= Path=/shop-type/**
#
## ����·��id
#spring.cloud.gateway.routes[3].id=service-blog
##����·�ɵ�uri
#spring.cloud.gateway.routes[3].uri=lb://service-blog
##����·�ɶ���,����servicerIdΪauth-service��/auth/·��
#spring.cloud.gateway.routes[3].predicates= Path=/blog/**
#
## ����·��id
#spring.cloud.gateway.routes[4].id=service-voucher
##����·�ɵ�uri
#spring.cloud.gateway.routes[4].uri=lb://service-voucher
##����·�ɶ���,����servicerIdΪauth-service��/auth/·��
#spring.cloud.gateway.routes[4].predicates= Path=/voucher/**
#
## ����·��id
#spring.cloud.gateway.routes[5].id=service-voucher
##����·�ɵ�uri
#spring.cloud.gateway.routes[5].uri=lb://service-voucher
##����·�ɶ���,����servicerIdΪauth-service��/auth/·��
#spring.cloud.gateway.routes[5].predicates= Path=/voucher-order/**
#
## ����·��id
#spring.cloud.gateway.routes[6].id=service-upload
##����·�ɵ�uri
#spring.cloud.gateway.routes[6].uri=lb://service-upload
##����·�ɶ���,����servicerIdΪauth-service��/auth/·��
#spring.cloud.gateway.routes[6].predicates= Path=/upload/**
#
## ����·��id
#spring.cloud.gateway.routes[7].id=service-follow
##����·�ɵ�uri
#spring.cloud.gateway.routes[7].uri=lb://service-follow
##����·�ɶ���,����servicerIdΪauth-service��/auth/·��
#spring.cloud.gateway.routes[7].predicates= Path=/follow/**